Repository bokjiri/back-end, pull requests merged in 2022-06, with the labels that each got.

#369 feat(youngwoo):기능 수정
  .gitignore
  API/guestbook/services/guestbook.service.js
  badWord.js
  openAPI/dataCleansing/cleansing.js
  openAPI/dataCleansing/data.js
  schemas/index.js
Labels: documentation, revise

#370 feat(user): Promise.all로 변경
  API/users/controllers/user.controller.js
Labels: revise

#371 feat(mail):test용 route 추가
  .gitignore
  API/mark/controllers/mark.controller.js
  API/mark/index.js
  API/mark/services/mark.service.js
  app.js
  schemas/index.js
  serverTest/loadtest.yml
  serverTest/mailertest.yml
Labels: documentation

#372 fix(detail): modify detail service
  API/policies/services/detail.service.js
Labels: bug

#373 feat(mail): schdule 추가
  API/mark/index.js
  API/mark/services/mark.service.js
  API/tip/services/tip.service.js
  app.js
Labels: documentation, revise

#374 feat(openAPI): Primise.all 속도 테스트
  openAPI/dataCleansing/cleansing.js
  openAPI/dataCleansing/data.js
Labels: help wanted

#375 feat(test):target 제거
  serverTest/mailertest.yml
Labels: documentation

#376 feat(openAPI): 구조정리
  .gitignore
  app.js
  openAPI/centralAPI/cleansing.js
  openAPI/centralAPI/controllers/central.age.js
  openAPI/centralAPI/controllers/central.controller.js
  openAPI/centralAPI/controllers/central.salary.js
  openAPI/centralAPI/index.js
  openAPI/dataCleansing/data.js
  openAPI/youthAPI/controllers/youth.controller.js
  openAPI/youthAPI/index.js
  openAPI/youthAPI/youth.local.js
  package-lock.json
  package.json
Labels: revise

#377 feat(test): testcode 수정
  API/mark/controllers/mark.spec.js
  API/tip/controllers/tip.spec.js
Labels: bug

#379 feat(app): app.js 오타수정
  app.js
Labels: bug

#378 fix(testcode):tip 통합테스트 수정
  API/tip/controllers/tip.controller.js
  API/tip/index.spec.js
  test/data/sample.json
Labels: revise

#380 fix(test.js): 이름 변경
  .gitignore
  stressTest/loadtest.yml
  stressTest/mailertest.yml
Labels: revise

#381 feat(mail): test시 메일계정 테스트 mail로 변경
  .github/workflows/node.js.yml
  API/mail/index.spec.js
  API/mail/services/mail.service.js
Labels: bug

#382 feat(dev):go main
  .github/workflows/node.js.yml
  .gitignore
  API/guestbook/services/guestbook.service.js
  API/mail/index.spec.js
  API/mail/services/mail.service.js
  API/mark/controllers/mark.controller.js
  API/mark/controllers/mark.spec.js
  API/mark/index.js
  API/mark/services/mark.service.js
  API/policies/services/detail.service.js
  API/tip/controllers/tip.controller.js
  API/tip/controllers/tip.spec.js
  API/tip/index.spec.js
  API/tip/services/tip.service.js
  API/users/controllers/user.controller.js
  app.js
  badWord.js
  openAPI/centralAPI/cleansing.js
  openAPI/centralAPI/controllers/central.age.js
  openAPI/centralAPI/controllers/central.controller.js
  openAPI/centralAPI/controllers/central.salary.js
  openAPI/centralAPI/index.js
  openAPI/dataCleansing/cleansing.js
  openAPI/dataCleansing/data.js
  openAPI/youthAPI/controllers/youth.controller.js
  openAPI/youthAPI/index.js
  openAPI/youthAPI/youth.local.js
  package-lock.json
  package.json
  schemas/index.js
  stressTest/loadtest.yml
  stressTest/mailertest.yml
  test/data/sample.json
Labels: documentation

#383 feat(test): timeout 설정
  API/mark/index.spec.js
  API/policies/index.spec.js
  API/tip/index.spec.js
Labels: bug

#384 fix(dev) to main from dev
  API/mark/index.spec.js
  API/policies/index.spec.js
  API/tip/index.spec.js
Labels: bug

#385 fix(README): update README file
  README.md
Labels: documentation

#386 feat(pm2): pm2 --watch 에서 reload로 변경
  scripts/after.install.sh
Labels: revise

#387 feat(package): 사용하지 않는 package 정리
  package-lock.json
  package.json
Labels: revise

#389 feat(https):.https 주석
  openAPI/centralAPI/index.js
  server.js
Labels: documentation

#390 feat(pm2):reload 주석
  scripts/after.install.sh
Labels: documentation

#392 feat(socket): test
  package-lock.json
  package.json
  server.js
  socket.js
Labels: documentation

#393 feat(socket):test
  app.js
  schemas/chat.js
  server.js
  socket.js
Labels: documentation

#394 feat(stresstest): 스트레스 테스트 경로 수정
  API/users/services/user.service.js
  app.js
  logging.js
  openAPI/centralAPI/index.js
  openAPI/youthAPI/index.js
  stressTest/loadtest.yml
Labels: documentation

#395 fix(socket): chatroom uerId 제거
  schemas/chat.js
  server.js
  socket.js
Labels: revise

#396 feat(test): testdb url 변경
  API/mail/index.spec.js
  API/mark/index.spec.js
  API/news/index.spec.js
  API/policies/index.spec.js
  API/search/index.spec.js
  API/tip/index.spec.js
  API/users/index.spec.js
Labels: bug

#397 feat(log): log 모양 변경
  app.js
Labels: revise

#398 feat(test): timeout 설정
  API/mail/index.spec.js
Labels: bug

#399 feat(service): trycatch error handling
  API/mark/services/mark.service.js
  API/news/services/news.service.js
  API/policies/services/detail.service.js
  API/tip/services/tip.service.js
  API/users/services/user.service.js
Labels: bug

#400 feat(pm2): pm2 clustermode 추가
  ecosystem.config.js
  ecosystem.json
  server.js
Labels: documentation

#401 feat(pm2): sudo pm2 reload server 추가
  scripts/after.install.sh
Labels: documentation

#402 feat(pm2): app -> server
  server.js
Labels: bug

#403 feat(CI): npm i -> npm ci
  .github/workflows/node.js.yml
Labels: revise

#404 Update README.md
  README.md
Labels: documentation

#405 feat(README) 비동기 처리 방식에 관한 문제 효과 링크 추가
  README.md
Labels: documentation

#406 feat(dev) to main from dev
  .github/workflows/node.js.yml
  API/mail/index.spec.js
  API/mark/index.spec.js
  API/mark/services/mark.service.js
  API/news/index.spec.js
  API/news/services/news.service.js
  API/policies/index.spec.js
  API/policies/services/detail.service.js
  API/search/index.spec.js
  API/tip/index.spec.js
  API/tip/services/tip.service.js
  API/users/index.spec.js
  API/users/services/user.service.js
  app.js
  ecosystem.config.js
  ecosystem.json
  logging.js
  openAPI/centralAPI/index.js
  openAPI/youthAPI/index.js
  package-lock.json
  package.json
  schemas/chat.js
  scripts/after.install.sh
  server.js
  socket.js
  stressTest/loadtest.yml
Labels: documentation

#407 feat(redis): TTL 720초로 수정
  API/mark/services/mark.service.js
  API/news/services/news.service.js
  API/policies/services/main.service.js
  API/users/services/user.service.js
Labels: revise

#408 feat(dev) to main from dev
  API/mark/services/mark.service.js
  API/news/services/news.service.js
  API/policies/services/main.service.js
  API/users/services/user.service.js
Labels: documentation

#410 Update README.md
  README.md
Labels: documentation

#411 feat(AWS-X-Ray) 하위세그먼트 추가
  API/users/controllers/user.controller.js
  API/users/controllers/user.controller.spec.js
  API/users/services/user.service.js
Labels: documentation

#412 feat(app) 헬멧 주석 해제
  app.js
Labels: revise
