Repository bokjiri/back-end, pull requests merged in 2022-04, with the labels that each got.

#9 feat(unitTset): create unit test code for TDD
  app.spec.js
  controllers/mainController.spec.js
  controllers/markController.spec.js
  controllers/tipController.spec.js
  controllers/userController.spec.js
  middlewares/users/auth-middleware.spec.js
  routes/index.spec.js
  routes/main.spec.js
  routes/mark.spec.js
  routes/tip.spec.js
  routes/user.spec.js
Labels: documentation

#12 feat(CD): consturcture for CD
  appspec.yml
  scripts/after.install.sh
Labels: bug

#13 feat(CD): consturcture for CD
  appspec.yml
  scripts/after.install.sh
Labels: bug

#15 feat(unitTset): create unit test code for TDD
  controllers/authController.js
  controllers/authController.spec.js
  controllers/mainController.js
  controllers/mainController.spec.js
  controllers/markController.js
  controllers/markController.spec.js
  controllers/tipController.js
  controllers/tipController.spec.js
  controllers/userController.js
  controllers/userController.spec.js
  middlewares/users/auth-middleware.spec.js
  routes/auth.js
  routes/auth.spec.js
  routes/index.js
  routes/mark.js
  routes/tip.js
  routes/user.js
Labels: documentation, enhancement

#17 feat(CD): setting for CD
  appspec.yml
  scripts/application.start.sh
  scripts/application.stop.sh
Labels: revise

#18 feat(unitTset): create unit test code for TDD
  controllers/authController.js
  controllers/authController.spec.js
  controllers/mainController.js
  controllers/mainController.spec.js
  controllers/markController.js
  controllers/markController.spec.js
  controllers/tipController.js
  controllers/tipController.spec.js
  controllers/userController.js
  controllers/userController.spec.js
  package-lock.json
  package.json
  prettier.config.js
Labels: documentation, invalid

#19 fix(basic): add folder structure
  controllers/auth.controller.js
  controllers/main.controller.js
  controllers/mark.controller.js
  controllers/specs/auth.spec.js
  controllers/specs/main.spec.js
  controllers/specs/mark.spec.js
  controllers/specs/tip.spec.js
  controllers/specs/user.spec.js
  controllers/tip.controller.js
  controllers/user.controller.js
  middlewares/users/auth-middleware.js
  package-lock.json
  package.json
  prettier.config.js
  routes/auth.js
  routes/main.js
  routes/mark.js
  routes/specs/auth.spec.js
  routes/specs/index.spec.js
  routes/specs/main.spec.js
  routes/specs/mark.spec.js
  routes/specs/tip.spec.js
  routes/specs/user.spec.js
  routes/tip.js
  routes/user.js
  services/auth.service.js
  services/main.service.js
  services/mark.service.js
  services/tip.service.js
  services/user.service.js
  test/data/new-auth.js
  test/data/new-main.js
  test/data/new-mark.js
  test/data/new-tip.js
  test/data/new-user.js
Labels: documentation, enhancement

#20 feat(DC): Data Cleansing
  openAPI/index.js
  openAPI/output.txt
  openAPI/output2.txt
  package-lock.json
  package.json
Labels: documentation

#21 feat(basicDB): change db to mongo
  app.js
  models/Char.js
  models/CharData.js
  models/CharUser.js
  models/Data.js
  models/Desire.js
  models/DesireData.js
  models/Life.js
  models/LifeData.js
  models/LifeUser.js
  models/Mark.js
  models/Obst.js
  models/ObstData.js
  models/ObstUser.js
  models/Tip.js
  models/Trgter.js
  models/TrgterData.js
  models/TrgterUser.js
  models/User.js
  models/index.js
  models/init-models.js
  openAPI/index.js
  openAPI/output.txt
  package-lock.json
  package.json
  schemas/data.js
  schemas/index.js
  schemas/user.js
  services/user.service.js
Labels: documentation

#23 feat(data): create data
  controllers/user.controller.js
  openAPI/index.js
  openAPI/output2.txt
  package-lock.json
  package.json
  schemas/autoidsetter.js
  schemas/data.js
  schemas/index.js
  schemas/user.js
  services/user.service.js
Labels: documentation

#24 feat(mongoDB): create mongoDB account
  schemas/index.js
Labels: documentation

#25 feat(auth): sign in sign up
  app.js
  controllers/auth.controller.js
  controllers/user.controller.js
  openAPI/index.js
  package-lock.json
  package.json
  routes/auth.js
  routes/mark.js
  routes/user.js
  schemas/index.js
  services/user.service.js
Labels: documentation

#26 feat(mark):test mongo
  app.js
  controllers/mark.controller.js
  routes/mark.js
  services/mark.service.js
Labels: documentation

#27 Auth
  controllers/user.controller.js
  routes/user.js
Labels: documentation

#28 feat(auth): cors
  app.js
Labels: bug

#29 feat(auth): cors
  app.js
Labels: bug

#30 feat(auth): redirect
  controllers/user.controller.js
Labels: revise

#31 feat(auth): cors
  app.js
  controllers/user.controller.js
  schemas/data.js
Labels: bug

#32 feat(auth): cors
  app.js
  controllers/user.controller.js
Labels: bug

#33 feat(auth): redirect
  app.js
  controllers/user.controller.js
Labels: bug

#35 feat(auth): cors
  app.js
Labels: bug

#37 Ssl
  app.js
  controllers/user.controller.js
  server.js
Labels: bug

#38 feat(ssl): https
  app.js
Labels: revise

#40 feat(cors): cors option revise
  app.js
Labels: bug

#41 feat(cors): cors option revise
  app.js
  controllers/user.controller.js
Labels: bug

#42 feat(cors): cors option revise
  app.js
Labels: bug

#43 feat(cors): cors option revise
  controllers/user.controller.js
Labels: bug

#45 feat(auth): sign in sign up
  controllers/user.controller.js
Labels: bug

#47 feat(auth): sign in sign up
  controllers/user.controller.js
Labels: bug

#49 feat(auth): sign in sign up
  app.js
  controllers/user.controller.js
Labels: bug

#50 feat(auth): sign in sign up
  controllers/auth.controller.js
Labels: bug

#51 feat(auth): sign in sign up
  app.js
Labels: bug

#52 feat(auth): sign in sign up
  controllers/auth.controller.js
Labels: bug

#53 feat(auth): sign in sign up
  controllers/user.controller.js
Labels: bug

#54 feat(auth): sign in sign up
  controllers/user.controller.js
Labels: bug

#55 feat(auth): sign in sign up
  controllers/user.controller.js
Labels: bug

#57 fix(mark):mark, unit test, Int test
  controllers/mark.controller.js
  controllers/specs/mark.spec.js
  routes/specs/mark.spec.js
  services/mark.service.js
Labels: documentation

#58 feat(authmiddleware): auth.middleware
  controllers/auth.controller.js
  controllers/specs/auth.spec.js
  controllers/specs/user.spec.js
  middlewares/auth/auth.middleware.js
  middlewares/auth/auth.middleware.spec.js
  middlewares/users/auth-middleware.js
  middlewares/users/auth-middleware.spec.js
  routes/auth.js
  routes/user.js
  server.js
  services/user.service.js
  test/data/new-user.js
  test/user/bearer.json
  test/user/empty.json
  test/user/incorrect.json
  test/user/invalid.json
  test/user/login.json
  test/user/new-user.js
Labels: documentation

#59 feat(server): https
  server.js
Labels: bug

#60 feat(server): local.js server.js split
  .gitignore
Labels: documentation
