Repository bokjiri/back-end, pull requests merged in 2022-05, with the labels that each got.

#63 feat(authmiddleware): auth.middleware refactoring
  middlewares/auth/auth.middleware.js
Labels: revise

#62 feat(mark): add redis
  controllers/mark.controller.js
  middlewares/redis.middleware.js
  routes/mark.js
  schemas/redis.js
  services/mark.service.js
Labels: documentation

#64 feat(mark): add top5 Mark
  controllers/mark.controller.js
  package-lock.json
  package.json
  routes/mark.js
  routes/tip.js
  services/mark.service.js
Labels: documentation

#65 feat(authmiddleware): auth.middleware refactoring
  middlewares/auth/auth.middleware.js
Labels: bug

#67 feat(user): add (put, delete, get ), delete household in schemas/user
  controllers/specs/user.spec.js
  controllers/user.controller.js
  middlewares/auth/auth.middleware.spec.js
  routes/user.js
  schemas/user.js
  services/user.service.js
  test/user/expieredaccess.json
  test/user/invalid.json
  test/user/new-user.js
Labels: documentation

#68 feat(mark) add mark like
  controllers/mark.controller.js
  middlewares/redis.middleware.js
  routes/mark.js
  schemas/user.js
  services/mark.service.js
Labels: documentation

#69 feat(mainAPI): develop main GET API
  controllers/main.controller.js
  services/main.service.js
Labels: documentation

#70 feat(tip):add tip
  controllers/mark.controller.js
  controllers/tip.controller.js
  services/tip.service.js
  tipLog.txt
Labels: documentation

#72 feat(workflows): workflows github secret 환경변수 추가
  .github/workflows/node.js.yml
  .prettierignore
Labels: documentation

#74 feat(openAPI): openAPI 추가
  .github/workflows/node.js.yml
  openAPI/area.js
  openAPI/chung5.txt
  openAPI/indexdex.js
  openAPI/test.js
  prettier.config.js
  schemas/data.js
Labels: documentation

#75 feat(auth): kakao login
  controllers/auth.controller.js
Labels: bug

#76 feat(user): check user
  services/user.service.js
Labels: bug

#78 feat(auth): kakao login
  controllers/auth.controller.js
Labels: bug

#79 feat(middlewares): middlewares res.locals 수정
  middlewares/auth/auth.middleware.js
Labels: bug

#80 feat(middlewares): middlewares res.locals 수정
  middlewares/auth/auth.middleware.js
  services/user.service.js
Labels: bug

#81 feat(openAPI): openAPI수정
  .gitignore
  openAPI/chung5.txt
  openAPI/indexdex.js
Labels: revise

#82 fix(mainAPI): getMain & add swagger, unit test
  controllers/main.controller.js
  controllers/specs/main.spec.js
  services/main.service.js
Labels: bug, documentation

#83 fix(mainAPI): modify getMain API url
  controllers/main.controller.js
  controllers/specs/main.spec.js
  routes/main.js
Labels: revise

#84 feat(detail): 상세정보조회 api 추가
  controllers/detail.controller.js
  routes/detail.js
  routes/index.js
  services/detail.service.js
Labels: documentation

#85 feat(github): log.txt
  .gitignore
  tipLog.txt
Labels: documentation

#86 fix(tip):txt file name 변경
  services/tip.service.js
Labels: documentation

#87 feat(news):news data
  app.js
  controllers/news.controller.js
  middlewares/redis.middleware.js
  package-lock.json
  package.json
  routes/index.js
  routes/news.js
Labels: documentation

#89 fix(mainAPI): checkedData includes undefined data
  services/main.service.js
Labels: bug

#92 fix(news): news 내용 수정
  controllers/news.controller.js
Labels: documentation

#93 fix(mainAPI): create category of checkedData
  controllers/main.controller.js
Labels: documentation, enhancement

#94 fix(mainAPI): cleansing checkedData
  controllers/main.controller.js
  services/main.service.js
Labels: bug, documentation

#95 fix(news): news 내용 수정
  controllers/news.controller.js
Labels: documentation

#96 fix(news): news 기능 수정
  controllers/news.controller.js
  schemas/news.js
Labels: documentation

#98 feat(news): news 기능 수정
  controllers/news.controller.js
Labels: documentation

#100 feat(user): user 수정
  controllers/user.controller.js
  schemas/user.js
  services/user.service.js
Labels: revise

#101 fix(mark):삭제기능 수정
  controllers/mark.controller.js
  controllers/news.controller.js
Labels: documentation

#102 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
  schemas/user.js
  services/mark.service.js
Labels: documentation

#103 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
  services/mark.service.js
Labels: documentation

#104 fix(mark):북마크 json 수정
  controllers/mark.controller.js
  openAPI/gender.js
  services/mark.service.js
Labels: documentation

#105 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
  services/mark.service.js
Labels: documentation

#106 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
Labels: documentation

#107 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
Labels: documentation

#108 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
Labels: documentation

#109 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
Labels: documentation

#110 fix(mark):북마크 삭제 수정
  controllers/mark.controller.js
  routes/mark.js
Labels: documentation

#112 feat(user): user 수정
  controllers/user.controller.js
  schemas/user.js
Labels: revise

#114 feat(user): user 수정
  schemas/data.js
  schemas/user.js
Labels: revise

#118 feat(news):node-schedule 자동 업데이트
  app.js
  controllers/news.controller.js
  middlewares/redis.middleware.js
  services/mark.service.js
  services/news.service.js
Labels: documentation

#119 fix(news):node-schedule tz설정
  openAPI/marriage.js
  services/news.service.js
Labels: revise

#120 feat(news):node-schedule 자동 업데이트
  services/news.service.js
Labels: revise

#121 fix(news):레디스 제거 테스트
  openAPI/marriage.js
  routes/news.js
  services/news.service.js
Labels: revise

#122 fix(news):try catch 추가
  controllers/news.controller.js
  services/news.service.js
Labels: documentation

#123 feat(openAPI): openAPI 수정
  openAPI/area.js
  openAPI/area2.js
  openAPI/index.youth.js
  schemas/data.js
  services/user.service.js
Labels: bug

#124 feat(news):뉴스 오류 수정
  routes/news.js
  services/news.service.js
Labels: revise

#125 fix(tips):버그제보 코드 보완
  controllers/tip.controller.js
  routes/tip.js
  services/news.service.js
  services/tip.service.js
Labels: documentation

#126 feat(user): userservice findOne console.log
  controllers/auth.controller.js
  controllers/specs/user.spec.js
  controllers/user.controller.js
  routes/user.js
  services/user.service.js
Labels: bug

#127 feat(user): userservice findOne
  controllers/auth.controller.js
  services/user.service.js
Labels: bug

#128 feat(swagger): create swagger
  controllers/detail.controller.js
  controllers/main.controller.js
  controllers/mark.controller.js
  controllers/news.controller.js
  controllers/tip.controller.js
Labels: documentation

#129 fix(swagger): create swagger
  .gitignore
  app.js
  swagger.js
Labels: bug

#130 fix(swagger): create swagger
  routes/main.js
Labels: bug

#131 feat(CD): hook에 swagger추가
  scripts/after.install.sh
Labels: documentation

#132 fix(mainAPI): modify forEach to for
  services/main.service.js
Labels: bug

#133 fix(mainAPI): add eliminate deduplication fn
  controllers/main.controller.js
  services/main.service.js
Labels: bug

#135 feat(openAPI): 제목으로 중복 제거
  controllers/user.controller.js
  openAPI/index.youth.js
  schemas/index.js
  schemas/user.js
  schemas/youth.js
  services/user.service.js
Labels: revise

#136 feat(user): user findOne -> find
  controllers/auth.controller.js
  services/user.service.js
Labels: bug

#137 feat(user): user find -> findOne
  controllers/auth.controller.js
  controllers/user.controller.js
  middlewares/auth/auth.middleware.js
  services/user.service.js
Labels: bug

#139 fix(news): news 데이터 정렬
  services/news.service.js
Labels: documentation

#140 fix(mainAPI): modify getMain
  controllers/main.controller.js
  services/main.service.js
Labels: documentation, revise

#141 fix(auth): 폴더구조 변경
  app.js
  controllers/detail.controller.js
  controllers/user.controller.js
  kakao/index.js
  routes/index.js
  services/detail.service.js
  services/user.service.js
Labels: revise

#142 fix(auth): 폴더구조 변경
  controllers/specs/auth.spec.js
  kakao/index.js
  kakao/strategy.js
  services/auth.service.js
Labels: revise

#143 feat(openAPI): 나이 기준 수정
  openAPI/index.youth.js
  schemas/data.js
Labels: revise

#144 feat(marriage):결혼 데이터 분류
  openAPI/gender.js
  openAPI/marriage.js
  openAPI/scholarship.js
  schemas/data.js
Labels: documentation

#145 feat(detail): detail res 변경
  controllers/detail.controller.js
  services/detail.service.js
Labels: revise

#146 feat(openAPI): 자동화
  app.js
  openAPI/crawling.js
  openAPI/index.youth.js
Labels: documentation

#147 feat(data):데이터 클렌징 코드 정리
  dataCleansing/cleansing.js
  dataCleansing/data.js
  openAPI/gender.js
  openAPI/jungbu24.js
  openAPI/scholarship.js
Labels: documentation

#148 feat(getMain): 조건 검사 로직 추가
  controllers/main.controller.js
  services/main.service.js
  services/search.service.js
Labels: documentation

#149 fix(getMain): region 조건 검사 오류 수정
  controllers/main.controller.js
Labels: bug

#151 feat(getMain): 조건 검사 로직 추가
  controllers/main.controller.js
Labels: documentation

#152 fix(getMain): 중복 제거 함수 오류 수정
  controllers/main.controller.js
Labels: bug

#153 feat(user): family 추가
  controllers/user.controller.js
  schemas/user.js
  services/user.service.js
Labels: documentation

#154 feat(CD): pm2 kill pm2 start 설정
  appspec.yml
  scripts/application.start.sh
  scripts/application.stop.sh
Labels: documentation

#155 feat(log): requests, error 로그 추가
  app.js
  controllers/mark.controller.js
  logging.js
  openAPI/jungbu24.js
  package-lock.json
  package.json
Labels: documentation

#156 feat(CD):hook 제거
  appspec.yml
Labels: bug

#158 feat(getMain): 조건 검사 로직 추가
  controllers/main.controller.js
  services/main.service.js
Labels: documentation

#159 fix(log): 로그파일 경로 수정
  logging.js
Labels: documentation

#160 feat(openAPI):자동화 적용
  app.js
  dataUpdating/index.js
  ecosystem.json
  openAPI/index.youth.js
Labels: bug

#161 feat(openAPI): openAPI log 위치 변경
  dataUpdating/index.js
Labels: revise

#162 feat(openAPI): 코드정리
  openAPI/index.youth.js
Labels: bug

#163 fix(tip): 버그제보 로그 경로 변경
  app.js
  controllers/tip.controller.js
  services/tip.service.js
Labels: documentation

#164 feat(openAPI): openAPI log 위치 변경
  dataUpdating/index.js
Labels: bug

#165 feat(openAPI): openAPI log 위치 환경변수 설정
  dataUpdating/index.js
Labels: revise

#166 feat(openAPI): openAPI 수정, 추가 및 scripts 변경
  dataUpdating/index.js
  openAPI/index.youth.js
  openAPI/jungbu.category.js
  openAPI/jungbu24.js
  scripts/after.install.sh
  scripts/application.start.sh
  scripts/application.stop.sh
Labels: bug, documentation, revise

#167 feat(CD): hook 변경
  scripts/after.install.sh
Labels: bug

#168 feat(CD): hook 변경
  scripts/after.install.sh
Labels: bug

#169 refactor(getMain): logic 조건 검사 코드 분리
  controllers/main.controller.js
Labels: revise

#170 fix(getMain): logic console.error 추가
  controllers/main.controller.js
  services/main.service.js
Labels: bug, documentation

#171 fix(getMain): salary 조건 검사 버그 수정
  controllers/main.controller.js
Labels: bug

#172 feat(search): 프론트 통신 테스트
  controllers/main.controller.js
  controllers/mark.controller.js
  controllers/search.controller.js
  routes/search.js
  services/search.service.js
Labels: documentation

#173 feat(검색): 검색기능 1차 완료!
  services/search.service.js
Labels: documentation

#175 feat(user): validator 추가
  controllers/user.controller.js
  routes/user.js
  services/detail.service.js
  services/user.service.js
  validator/user.validator.js
Labels: documentation

#176 feat(mark,news): authmiddleware 추가
  controllers/mark.controller.js
  controllers/news.controller.js
  routes/mark.js
  routes/news.js
Labels: documentation

#177 feat(user): validator 추가, logging 추가
  controllers/detail.controller.js
  controllers/user.controller.js
  validator/region.js
  validator/user.validator.js
Labels: documentation

#178 fix(mark):router 경로 재설정
  controllers/mark.controller.js
  routes/mark.js
Labels: documentation

#179 fix(mark): 유저 검사 수정
  controllers/mark.controller.js
Labels: documentation

#180 feat(user): validator 추가
  validator/user.validator.js
  validator/validator.array.js
Labels: documentation

#181 feat(tip):로그남기기 추가
  controllers/mark.controller.js
  controllers/tip.controller.js
Labels: documentation

#182 feat(mail): 메일보내기 추가, fix(openAPI): 받을 때마다 정보가 달라지던 문제 수정
  controllers/mail.controller.js
  dataUpdating/index.js
  openAPI/index.youth.js
  package-lock.json
  package.json
  routes/index.js
  routes/mail.js
  services/mail.service.js
  swagger.js
Labels: bug, documentation

#185 fix(getMain): Error logging
  controllers/main.controller.js
Labels: bug

#184 feat(user): stack error 추가
  controllers/detail.controller.js
  controllers/mail.controller.js
  controllers/user.controller.js
Labels: documentation

#183 feat(dev): to main from dev
  app.js
  controllers/detail.controller.js
  controllers/mail.controller.js
  controllers/main.controller.js
  controllers/mark.controller.js
  controllers/news.controller.js
  controllers/search.controller.js
  controllers/tip.controller.js
  controllers/user.controller.js
  dataUpdating/index.js
  logging.js
  openAPI/index.youth.js
  openAPI/jungbu.category.js
  openAPI/jungbu24.js
  package-lock.json
  package.json
  routes/index.js
  routes/mail.js
  routes/mark.js
  routes/news.js
  routes/search.js
  routes/user.js
  schemas/user.js
  scripts/after.install.sh
  scripts/application.start.sh
  scripts/application.stop.sh
  services/detail.service.js
  services/mail.service.js
  services/main.service.js
  services/search.service.js
  services/tip.service.js
  services/user.service.js
  swagger.js
  validator/user.validator.js
  validator/validator.array.js
Labels: documentation

#186 feat(mail): require 삭제
  services/mail.service.js
Labels: bug

#188 fix(mark):프론트 상태저장 응답값 추가
  controllers/mark.controller.js
Labels: documentation

#189 fix(mark): 프론트 상태 응답변경
  controllers/mark.controller.js
  services/mark.service.js
Labels: documentation

#190 fix(dev): mark modify to main from dev
  controllers/mark.controller.js
  services/mark.service.js
Labels: documentation

#191 feat(user): validation 수정
  validator/user.validator.js
Labels: bug

#192 feat(user): validation 수정
  validator/validator.array.js
Labels: bug

#193 feat(user): validation 수정
  validator/user.validator.js
Labels: bug

#194 feat(user): get 할때 시·군을 선택해 주세요 추가
  controllers/user.controller.js
Labels: bug

#195 fix(dev): to main from dev
  controllers/user.controller.js
  validator/user.validator.js
  validator/validator.array.js
Labels: bug, hotfixes

#197 feat(getMain):북마크 여부 체크
  controllers/main.controller.js
  services/main.service.js
Labels: documentation

#202 feat(user): user
  controllers/user.controller.js
Labels: revise

#203 feat(dev): to main from dev
  controllers/user.controller.js
Labels: revise

#204 feat(search): 검색기능 수정
  app.js
  controllers/mark.controller.js
  controllers/search.controller.js
  dataCleansing/cleansing.js
  dataCleansing/data.js
  services/mark.service.js
Labels: bug

#206 fix(getMain):북마크 여부 체크 오류 수정
  services/main.service.js
Labels: bug

#207 feat(dev): to main from dev
  services/main.service.js
Labels: documentation

#208 feat(swagger): create user, search swagger
  controllers/detail.controller.js
  controllers/mark.controller.js
  controllers/search.controller.js
  controllers/user.controller.js
Labels: bug, documentation

#209 feat(detail): detail 북마크 상태값 추가
  controllers/detail.controller.js
  routes/user.js
  services/detail.service.js
Labels: documentation

#210 feat(dev): to main from dev
  controllers/detail.controller.js
  controllers/mark.controller.js
  controllers/search.controller.js
  controllers/user.controller.js
  routes/user.js
  services/detail.service.js
Labels: documentation

#211 fix(북마크):코드 수정
  controllers/mark.controller.js
  services/mark.service.js
Labels: bug

#212 feat(dev): to main from dev
  controllers/mark.controller.js
  services/mark.service.js
Labels: revise

#216 feat(user): 테스트코드 추가
  controllers/detail.controller.js
  controllers/specs/detail.spec.js
  controllers/specs/user.spec.js
  controllers/user.controller.js
  openAPI/prac.js
  package.json
Labels: documentation

#215 Pooreumu patch 1
  .github/workflows/dev.node.js.yml
Labels: documentation

#217 fix(getMain): getMain logic 오류 수정
  controllers/main.controller.js
Labels: bug

#218 feat(openAPI): axios로 변경
  dataUpdating/index.js
  openAPI/index.js
  validator/validator.array.js
Labels: bug, revise

#219 refactor(getMain): getMain logic 코드 리펙토링
  controllers/main.controller.js
Labels: revise

#220 feat(openAPI): 자동화 환경변수 추가
  app.js
  dataCleansing/data.js
  dataUpdating/index.js
  openAPI/index.age.js
  openAPI/index.js
Labels: documentation

#222 feat(githubAction): yml파일 두개라 테스트 2번하는 문제 수정
  .github/workflows/dev.node.js.yml
  .github/workflows/node.js.yml
Labels: bug

#223 feat(dev): to main from dev
  .github/workflows/node.js.yml
  app.js
  controllers/detail.controller.js
  controllers/main.controller.js
  controllers/specs/detail.spec.js
  controllers/specs/user.spec.js
  controllers/user.controller.js
  dataCleansing/data.js
  dataUpdating/index.js
  openAPI/index.age.js
  openAPI/index.js
  openAPI/prac.js
  package.json
  validator/validator.array.js
Labels: documentation

#224 feat(openAPI): salary 추가
  openAPI/index.salary.js
Labels: documentation

#226 fix(getMain): getMain age logic 수정
  controllers/main.controller.js
Labels: bug

#227 feat(getMain): getMain dismatchData 기능 추가
  services/main.service.js
Labels: documentation

#228 feat(dev): to main from dev
  controllers/main.controller.js
  openAPI/index.salary.js
  openAPI/jungbu24.js
  services/main.service.js
Labels: bug, documentation

#229 feat(testcode,mark,datacleansing)
  controllers/mark.controller.js
  controllers/specs/mark.spec.js
  controllers/specs/tip.spec.js
  controllers/tip.controller.js
  dataCleansing/cleansing.js
  dataCleansing/data.js
  routes/mark.js
  schemas/data.js
  services/mark.service.js
  services/tip.service.js
Labels: documentation, revise

#230 feat(getMain): getMain salary 조건 검사 정교화
  controllers/main.controller.js
  services/main.service.js
Labels: documentation, revise

#231 feat(openAPI): age 추가
  openAPI/index.age.js
  openAPI/index.js
  openAPI/index.salary.js
  schemas/data.js
Labels: documentation

#233 feat(openAPI): salary 추가중
  dataUpdating/youth.age.js
  openAPI/index.age.js
  openAPI/index.js
  openAPI/index.salary.js
Labels: documentation

#234 feat(mark): bookmarkState
  controllers/mark.controller.js
  controllers/specs/mark.spec.js
  routes/mark.js
Labels: revise

#235 feat(user): user 정보 workType 추가
  controllers/detail.controller.js
  controllers/user.controller.js
  openAPI/index.salary.js
  schemas/user.js
  services/user.service.js
  validator/user.validator.js
  validator/validator.array.js
Labels: documentation

#236 feat(user): 오타수정
  validator/user.validator.js
Labels: bug

#237 feat(getMain): getMain workType logic 추가
  controllers/main.controller.js
  controllers/specs/main.spec.js
Labels: documentation

#238 feat(openAPI): 제한없음 조건 수정
  controllers/specs/user.spec.js
  dataUpdating/index.js
  dataUpdating/youth.age.js
Labels: revise

#239 feat(test):테스트코드 보완
  controllers/search.controller.js
  controllers/specs/mark.spec.js
  controllers/specs/news.spec.js
  controllers/specs/tip.spec.js
  controllers/tip.controller.js
  routes/specs/mark.spec.js
  services/mark.service.js
Labels: documentation

#240 feat(user): 회원가입 로그인 인증메일발송 인증코드 검증 추가
  controllers/mail.controller.js
  controllers/specs/detail.spec.js
  controllers/user.controller.js
  routes/mail.js
  routes/specs/user.spec.js
  routes/user.js
  schemas/user.js
  services/mail.service.js
  services/user.service.js
Labels: documentation

#241 feat(search): 특수문자 제외
  controllers/search.controller.js
Labels: revise

#242 feat(user): 통합테스트 추가
  package-lock.json
  package.json
  routes/specs/user.spec.js
  schemas/index.js
Labels: documentation
